In [1]:
import nltk 

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

- collect some text 
- word_tokenize
- Sentence_tokenize(optional)
- Lower text 
- cleaning the text 
- Removing stop words 
- Stemming 
- Lemmatization 
- Bag-of-words
- Tf-Idf
- Padding in NLP 
- parts of speech 
- Developing Models 
    - Deep learning RNN 
    - Deep learning LSTM RNN 
    - Deep learning Bidirectinal LSTM RNN 
    

### Collect Text 

In [9]:
text = """Python tutorial provides basic and advanced concepts of Python. Our Python tutorial is designed for beginners and professionals.Python is a simple, general purpose, high level, and object-oriented programming language.Python is an interpreted scripting language also. Guido Van Rossum is known as the founder of Python programming."""

In [15]:
text

'Python tutorial provides basic and advanced concepts of Python. Our Python tutorial is designed for beginners and professionals.Python is a simple, general purpose, high level, and object-oriented programming language.Python is an interpreted scripting language also. Guido Van Rossum is known as the founder of Python programming.'

In [16]:
text[0]

'P'

### Sent_tokenize 

In [12]:
from nltk.tokenize import sent_tokenize

In [17]:
sent_text = sent_tokenize(text)

In [18]:
sent_text

['Python tutorial provides basic and advanced concepts of Python.',
 'Our Python tutorial is designed for beginners and professionals.Python is a simple, general purpose, high level, and object-oriented programming language.Python is an interpreted scripting language also.',
 'Guido Van Rossum is known as the founder of Python programming.']

In [19]:
sent_text[0]

'Python tutorial provides basic and advanced concepts of Python.'

### Word_tokenize

In [20]:
text

'Python tutorial provides basic and advanced concepts of Python. Our Python tutorial is designed for beginners and professionals.Python is a simple, general purpose, high level, and object-oriented programming language.Python is an interpreted scripting language also. Guido Van Rossum is known as the founder of Python programming.'

In [21]:
from nltk.tokenize import word_tokenize

In [22]:
word_tokenize(text)

['Python',
 'tutorial',
 'provides',
 'basic',
 'and',
 'advanced',
 'concepts',
 'of',
 'Python',
 '.',
 'Our',
 'Python',
 'tutorial',
 'is',
 'designed',
 'for',
 'beginners',
 'and',
 'professionals.Python',
 'is',
 'a',
 'simple',
 ',',
 'general',
 'purpose',
 ',',
 'high',
 'level',
 ',',
 'and',
 'object-oriented',
 'programming',
 'language.Python',
 'is',
 'an',
 'interpreted',
 'scripting',
 'language',
 'also',
 '.',
 'Guido',
 'Van',
 'Rossum',
 'is',
 'known',
 'as',
 'the',
 'founder',
 'of',
 'Python',
 'programming',
 '.']

In [25]:
a = text.split()  # defaulty works with (.)
a

['Python',
 'tutorial',
 'provides',
 'basic',
 'and',
 'advanced',
 'concepts',
 'of',
 'Python.',
 'Our',
 'Python',
 'tutorial',
 'is',
 'designed',
 'for',
 'beginners',
 'and',
 'professionals.Python',
 'is',
 'a',
 'simple,',
 'general',
 'purpose,',
 'high',
 'level,',
 'and',
 'object-oriented',
 'programming',
 'language.Python',
 'is',
 'an',
 'interpreted',
 'scripting',
 'language',
 'also.',
 'Guido',
 'Van',
 'Rossum',
 'is',
 'known',
 'as',
 'the',
 'founder',
 'of',
 'Python',
 'programming.']

### Lower the text 

In [26]:
a = 'KAMAL'

B = 'kamal'

In [28]:
text

'Python tutorial provides basic and advanced concepts of Python. Our Python tutorial is designed for beginners and professionals.Python is a simple, general purpose, high level, and object-oriented programming language.Python is an interpreted scripting language also. Guido Van Rossum is known as the founder of Python programming.'

In [29]:
text_lower = text.lower()

In [30]:
text_lower

'python tutorial provides basic and advanced concepts of python. our python tutorial is designed for beginners and professionals.python is a simple, general purpose, high level, and object-oriented programming language.python is an interpreted scripting language also. guido van rossum is known as the founder of python programming.'

### Cleaning the text 

In [31]:
import string

In [32]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [37]:
cleaned_text = ''.join([i for i in text_lower if i not in string.punctuation ])
cleaned_text

'python tutorial provides basic and advanced concepts of python our python tutorial is designed for beginners and professionalspython is a simple general purpose high level and objectoriented programming languagepython is an interpreted scripting language also guido van rossum is known as the founder of python programming'

In [39]:
a = []
for i in text_lower:
    if i not in string.punctuation:
        a.append(i)
b = ''.join(a)
print(b)
        

python tutorial provides basic and advanced concepts of python our python tutorial is designed for beginners and professionalspython is a simple general purpose high level and objectoriented programming languagepython is an interpreted scripting language also guido van rossum is known as the founder of python programming


In [40]:
cleaned_text

'python tutorial provides basic and advanced concepts of python our python tutorial is designed for beginners and professionalspython is a simple general purpose high level and objectoriented programming languagepython is an interpreted scripting language also guido van rossum is known as the founder of python programming'

### Removing stop words 

In [41]:
from nltk.corpus import stopwords

In [43]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\korla\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [44]:
stopwords = stopwords.words('english')  # 179
stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [45]:
len(stopwords)

179

In [46]:
cleaned_text

'python tutorial provides basic and advanced concepts of python our python tutorial is designed for beginners and professionalspython is a simple general purpose high level and objectoriented programming languagepython is an interpreted scripting language also guido van rossum is known as the founder of python programming'

In [47]:
a = word_tokenize(cleaned_text)
a

['python',
 'tutorial',
 'provides',
 'basic',
 'and',
 'advanced',
 'concepts',
 'of',
 'python',
 'our',
 'python',
 'tutorial',
 'is',
 'designed',
 'for',
 'beginners',
 'and',
 'professionalspython',
 'is',
 'a',
 'simple',
 'general',
 'purpose',
 'high',
 'level',
 'and',
 'objectoriented',
 'programming',
 'languagepython',
 'is',
 'an',
 'interpreted',
 'scripting',
 'language',
 'also',
 'guido',
 'van',
 'rossum',
 'is',
 'known',
 'as',
 'the',
 'founder',
 'of',
 'python',
 'programming']

In [49]:
stopwords_text = ' '.join([i for i in a if i not in stopwords])

In [51]:
cleaned_text

'python tutorial provides basic and advanced concepts of python our python tutorial is designed for beginners and professionalspython is a simple general purpose high level and objectoriented programming languagepython is an interpreted scripting language also guido van rossum is known as the founder of python programming'

In [50]:
stopwords_text

'python tutorial provides basic advanced concepts python python tutorial designed beginners professionalspython simple general purpose high level objectoriented programming languagepython interpreted scripting language also guido van rossum known founder python programming'

### Stemming 

In [52]:
from nltk.stem.porter import PorterStemmer

In [53]:
po_stem = PorterStemmer()

In [56]:
n = ['caring','care','cared']
for i in n:
    print('Original_name = ',i,'Stemming_words = ',po_stem.stem(i))

Original_name =  caring Stemming_words =  care
Original_name =  care Stemming_words =  care
Original_name =  cared Stemming_words =  care


In [59]:
a = stopwords_text.split()
for i in a:
    print("Original_word = " , i , "stemming word = ",po_stem.stem(i))
    


Original_word =  python stemming word =  python
Original_word =  tutorial stemming word =  tutori
Original_word =  provides stemming word =  provid
Original_word =  basic stemming word =  basic
Original_word =  advanced stemming word =  advanc
Original_word =  concepts stemming word =  concept
Original_word =  python stemming word =  python
Original_word =  python stemming word =  python
Original_word =  tutorial stemming word =  tutori
Original_word =  designed stemming word =  design
Original_word =  beginners stemming word =  beginn
Original_word =  professionalspython stemming word =  professionalspython
Original_word =  simple stemming word =  simpl
Original_word =  general stemming word =  gener
Original_word =  purpose stemming word =  purpos
Original_word =  high stemming word =  high
Original_word =  level stemming word =  level
Original_word =  objectoriented stemming word =  objectori
Original_word =  programming stemming word =  program
Original_word =  languagepython stemm

### Lemmatization 

In [60]:
from nltk.stem import WordNetLemmatizer

In [61]:
word_lem = WordNetLemmatizer()

In [63]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\korla\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [64]:
n = ['caring','care','cared']
for i in n:
    print('Original_name = ',i,'Stemming_words = ',word_lem.lemmatize(i))

Original_name =  caring Stemming_words =  caring
Original_name =  care Stemming_words =  care
Original_name =  cared Stemming_words =  cared


In [65]:
b = stopwords_text.split()
for i in a:
    print("Original_word = " , i , "stemming word = ",word_lem.lemmatize(i))
    


Original_word =  python stemming word =  python
Original_word =  tutorial stemming word =  tutorial
Original_word =  provides stemming word =  provides
Original_word =  basic stemming word =  basic
Original_word =  advanced stemming word =  advanced
Original_word =  concepts stemming word =  concept
Original_word =  python stemming word =  python
Original_word =  python stemming word =  python
Original_word =  tutorial stemming word =  tutorial
Original_word =  designed stemming word =  designed
Original_word =  beginners stemming word =  beginner
Original_word =  professionalspython stemming word =  professionalspython
Original_word =  simple stemming word =  simple
Original_word =  general stemming word =  general
Original_word =  purpose stemming word =  purpose
Original_word =  high stemming word =  high
Original_word =  level stemming word =  level
Original_word =  objectoriented stemming word =  objectoriented
Original_word =  programming stemming word =  programming
Original_wor

### Parts of speech 

In [69]:
a = ['I am an data scietist']

In [70]:
from nltk import pos_tag

In [74]:
sol = pos_tag(a)
sol

[('I am an data scietist', 'NN')]

### Converting text into Vectors [Numbers]

- Bag-of-words 
- TF-IDF
- Padding 

### 1. Bag of Words 

In [7]:
a = ["good boy",
    "good girl",
    "Boy girl good"]



In [8]:
a

['good boy', 'good girl', 'Boy girl good']

In [10]:
import sklearn

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv = CountVectorizer()

In [13]:
x = cv.fit_transform(a)

In [14]:
x

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [15]:
x.toarray()

array([[1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]], dtype=int64)

In [18]:
cv.vocabulary_

{'good': 2, 'boy': 0, 'girl': 1}

In [19]:
a

['good boy', 'good girl', 'Boy girl good']

### TF-IDF

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tf_idf = TfidfVectorizer()

In [23]:
a

['good boy', 'good girl', 'Boy girl good']

In [24]:
x = tf_idf.fit_transform(a)

In [25]:
tf_idf.vocabulary_

{'good': 2, 'boy': 0, 'girl': 1}

In [26]:
x.toarray()

array([[0.78980693, 0.        , 0.61335554],
       [0.        , 0.78980693, 0.61335554],
       [0.61980538, 0.61980538, 0.48133417]])

In [27]:
x

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

## WordEmbedding 1.Padding or pad_sequence 

In [28]:
import tensorflow 

In [30]:
from tensorflow import keras 

In [31]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [32]:
docs = ['Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']

In [33]:
docs

['Well done!',
 'Good work',
 'Great effort',
 'nice work',
 'Excellent!',
 'Weak',
 'Poor effort!',
 'not good',
 'poor work',
 'Could have done better.']

In [34]:
docs[0]

'Well done!'

In [35]:
###  taking vocabulary(dictionary size())

voc_size = 100
Embed_docs = [one_hot(d,voc_size) for d in docs]
print(Embed_docs)


[[70, 49], [88, 92], [8, 76], [56, 92], [68], [75], [25, 76], [39, 88], [25, 92], [29, 10, 49, 89]]


### Padding 

In [37]:
docs[0]
len(docs[0])

10

In [39]:
for i,j in enumerate(docs):
    print(j,'---------->',len(docs[i]))

Well done! ----------> 10
Good work ----------> 9
Great effort ----------> 12
nice work ----------> 9
Excellent! ----------> 10
Weak ----------> 4
Poor effort! ----------> 12
not good ----------> 8
poor work ----------> 9
Could have done better. ----------> 23


In [40]:
###  taking vocabulary(dictionary size())

voc_size = 100
Embed_docs = [one_hot(d,voc_size) for d in docs]
print(Embed_docs)


[[70, 49], [88, 92], [8, 76], [56, 92], [68], [75], [25, 76], [39, 88], [25, 92], [29, 10, 49, 89]]


In [43]:
## sentence should be of same length

sent_length = 5

Embd_doc_pad = pad_sequences(Embed_docs,maxlen=sent_length,padding='post')  # pre means begining

print(Embd_doc_pad)




[[70 49  0  0  0]
 [88 92  0  0  0]
 [ 8 76  0  0  0]
 [56 92  0  0  0]
 [68  0  0  0  0]
 [75  0  0  0  0]
 [25 76  0  0  0]
 [39 88  0  0  0]
 [25 92  0  0  0]
 [29 10 49 89  0]]
